### ISSUE TITLE
Update version gives error 

### ISSUE THREAD

**Issue by expoders8** [LecleVietnam/LeclePackageIssue#1]
I am using your package from version [0.0.2] , after you update version to 0.3.2+4 it's working fine but after you update package to 0.3.2+5 then it gives error in my code and not able to solve that error .
If I remove your package then my code is working fine.

 **_Below mentions the error_**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:latest.release.
     Required by:
         project :app > project :lecle_social_share
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

_**In result I found one solution**_  that is to add jcenter() && maven { url "https://maven.google.com/"}  in build.gradle file 

**************************************************************************************************************************************

 **_After adding the jCenter() to build.gradle file I get new error which mentions below_** 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for com.facebook.android:facebook-login:14.0.0: Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

***********************************************************************************

I tried every thing whatever StackOverflow show me but not able to solve this error please give me suggestion to solve this error.

Thank you for your support 👍

- Also I have one suggestion related to package :- I want to suggest lecle team to add one feature like send text with photo to all platform (whatsapp, facebook, telegram, twitter ).  Please refer this link for this new feature : [](https://pub.dev/packages/share_plus)

**Comment by kishancodealchemy** [comment]
Same issue

**Comment by LecleVietnam** [comment]
Hi @expoders8 and @kishancodealchemy, our team very appreciate for your feedbacks, we will work to fix this issue and research to add your suggested feature. We will notice you all when the new update is ready.

**Comment by expoders8** [comment]
@LecleVietnam @kishancodealchemy  Today I changes build.gradle file like below then error fixed 

Add this line to build.bradle file :- 

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
            google()
            mavenCentral() // New line
            maven { url 'https://maven.fabric.io/public' }
            jcenter()
    }
   dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral() // New line
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }
}
..
..
..
..
..


- after the adding this line in file, open terminal and run this two command :- Flutter clean & flutter pub get
- completing this two step then close your project and reopen it then re run this two command and also run flutter run  command after that two command.
- then your project is not giving the error it's run perfectly.



I don't know how it works because I already tried this same Solutions tomorrow but it is not working.

Thank you for support 👍 
Please add new Feature what I suggested, it is more helpful us to share text with image.
Thank You @LecleVietnam team 👍 👍

**Comment by LecleVietnam** [comment]
Hi @expoders8 thank you for your feedback, our team will consider your suggested feature and working on it asap.
