### ISSUE TITLE
lecle_yoyo_player, please provide an option to disable preferredOrientations change in player

### ISSUE THREAD

**Issue by ShawnYsp** [LecleVietnam/LeclePackageIssue#10]
The player forced to update preferredOrientations to portrait and landscape, which will override app's own setting for origination.

Please provide an option to disable preferredOrientations change. Thanks

**Comment by LecleVietnam** [comment]
Hi @yspshawn,
Did you mean that you want us to give the option to disable the full screen button on the video player?

**Comment by ShawnYsp** [comment]
Thank you, in video.dart line 306, this line will override app's orientations setting, please provide an option to disable it.

`    SystemChrome.setPreferredOrientations(DeviceOrientation.values);
`

**Comment by LecleVietnam** [comment]
Hi @yspshawn,
Thank you for the information we will have an update for this issue. We will notify you when the update is available on pub.dev.

**Comment by LecleVietnam** [comment]
Hi @yspshawn,
We have updated the package based on your suggestion. Could you please update the package's version and check this issue again. Thank you.

Note: You can now enable or disable the preferredOrientations override using the `enableSystemOrientationsOverride` property in the VideoStyle class. Besides, we have provided a property to add a custom orientation list called  `orientation` in VideoStyle class if you want to use your own orientation.

**Comment by ShawnYsp** [comment]
thank you!
