### ISSUE TITLE
the player has not been converted to null

### ISSUE THREAD

**Issue by nurmeev** [LecleVietnam/LeclePackageIssue#15]
`The current Dart SDK version is 3.0.0-218.1.beta.

Because televizor depends on yoyo_player >=0.0.2 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.`

Heeeeeeeeeeelp

**Comment by LecleVietnam** [comment]
Hi @nurmeev,

The yoyo_player package is an old package and it will never be maintained anymore. Therefore, our team has migrated it to lecle_yoyo_player package. Could you please change your package from yoyo_player to our team package [here](https://pub.dev/packages/lecle_yoyo_player) and check this issue again? If there is any issue occurs please create an issue here, we will try to support it asap.

Thank you.
