### ISSUE TITLE
Building for iOS Simulator, but linking in dylib built for iOS

### ISSUE THREAD

**Issue by devolonter** [LecleVietnam/LeclePackageIssue#2]
Can you add a build for the simulator, please?

**Comment by LecleVietnam** [comment]
Hi @devolonter, can you provide some more information for this issue, please? Our team will consider them and if possible we will start working on this issue asap.

**Comment by devolonter** [comment]
Hello,

The library provided binaries only for the ARM architecture, so when I connect your library to the project, I can't build the project for the simulator any more, only for real devices. Thanks!

**Comment by LecleVietnam** [comment]
Hi @devolonter, can you tell us which package are you using?

**Comment by devolonter** [comment]
I use lecle_social_share package

**Comment by LecleVietnam** [comment]
Hi @devolonter, thank you for the information. We will take a look and working on this issue asap.

**Comment by LecleVietnam** [comment]
Hi @devolonter, we have fixed this issue and released the fix in the latest version of the lecle_social_share package to pub.dev, you can update the package version and check this issue again.

**Comment by devolonter** [comment]
Hi @LecleVietnam,
I'll check it out soon. Thanks for the fast fix!

**Comment by devolonter** [comment]
Everything is fine! Thank you!
