### ISSUE TITLE
yoyo_player build error on flutter 3.10

### ISSUE THREAD

**Issue by ShawnYsp** [LecleVietnam/LeclePackageIssue#23]
The package **orientation** yoyo_player depends on caused the error, it used deprecated api.

Please fix, thanks

**Comment by sefidgaran** [comment]
Hi @LecleVietnam 

Have you had a chance to take a look into this issue?
Is this package going to be abandoned?

**Comment by h4ck0v3rflow** [comment]
Getting Same error, @LecleVietnam please update this 

/C:/Users/Dell/AppData/Local/Pub/Cache/hosted/pub.dev/orientation-1.3.0/lib/orientation.dart:23:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
      SystemChrome.setEnabledSystemUIOverlays(overlays);
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25m 24s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hydev777** [comment]
Same issue here

**Comment by LecleVietnam** [comment]
We have just updated to a new version. Sorry for the inconvenience

> Getting Same error, @LecleVietnam please update this
> 
> /C:/Users/Dell/AppData/Local/Pub/Cache/hosted/pub.dev/orientation-1.3.0/lib/orientation.dart:23:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'. SystemChrome.setEnabledSystemUIOverlays(overlays); ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> Target kernel_snapshot failed: Exception 2
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 25m 24s Exception: Gradle task assembleDebug failed with exit code 1

**Comment by LecleVietnam** [comment]
We have just updated to a new version. Sorry for the inconvenience
