### ISSUE TITLE
New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by subarnaPdl** [LecleVietnam/LeclePackageIssue#26]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

Lots of developers are not being able to update app on app store connect because of this issue. Lets fix it asap.

Reference link from app store:
https://developer.apple.com/documentation/uikit/uiwebview

Thank you for the package.

**Comment by subarnaPdl** [comment]
<img width="710" alt="Screenshot 2023-07-09 at 13 05 33" src="https://github.com/LecleVietnam/LeclePackageIssue/assets/82575511/65a6ac54-bd6f-4c40-a9ea-a5f13a559a91">

**Comment by LecleVietnam** [comment]
please, tell me what package you want to update

**Comment by LecleVietnam** [comment]
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.
> 
> Lots of developers are not being able to update app on app store connect because of this issue. Lets fix it asap.
> 
> Reference link from app store: https://developer.apple.com/documentation/uikit/uiwebview
> 
> Thank you for the package.

please, tell me the package which you want to update

**Comment by PasqualeTotaro** [comment]
This plugin uses multiple packages that have not been migrated to WkWebView. Can you please update?

**Comment by subarnaPdl** [comment]
It would be better if you fixed all the packages.  Currently, I am using these three, and they seem to be causing the issue:

LecleSocialShare.F.shareFileToFacebook()
LecleSocialShare.M.shareFileToMessenger()
LecleSocialShare.W.shareFileToWhatsApp()

Thank you for your attention to this matter.

**Comment by PasqualeTotaro** [comment]
> It would be better if you fixed all the packages. Currently, I am using these three, and they seem to be causing the issue:
> 
> LecleSocialShare.F.shareFileToFacebook() LecleSocialShare.M.shareFileToMessenger() LecleSocialShare.W.shareFileToWhatsApp()
> 
> Thank you for your attention to this matter.

Sorry here I meant that the opener of the plugin should fix this. Or at least can they give us access to the source code, so that we can update the packages causing the issue?

**Comment by PasqualeTotaro** [comment]
In addition, I wanted to mention that the packages that appear to be causing the issue are the Facebook Core SDK, Facebook Share SDK and Twitter SDK. It is just a matter to update these packages should be easy.

@LecleVietnam can you help with this?

**Comment by LecleVietnam** [comment]
> 



> 



> It would be better if you fixed all the packages. Currently, I am using these three, and they seem to be causing the issue:
> 
> LecleSocialShare.F.shareFileToFacebook() LecleSocialShare.M.shareFileToMessenger() LecleSocialShare.W.shareFileToWhatsApp()
> 
> Thank you for your attention to this matter.

We have just retested our package. we think the reason which you cannot share the file to Facebook is due to missing configuration. Please follow the link below. Remember to replace 1234 in 'com.facebook.app.FacebookContentProvider1234' = com.facebook.app.FacebookContentProvider{App ID}.

![image](https://github.com/LecleVietnam/LeclePackageIssue/assets/116162195/57e2323b-90a6-439e-b256-140a2aabbf6c)

https://developers.facebook.com/docs/android/getting-started#quick-start

Have a nice day ^^

**Comment by PasqualeTotaro** [comment]
@LecleVietnam I think the issue we are describing here is that the App cannot be pushed onto apple store, because it is still using deprecated APIs.

I managed to get it running changing this in **lecle_social_share.podspec**. Made sure to run all latest sdks. Twitter official sdk still fails, so I chose another one that is updated. I don't use twitter functions, so if you do make sure the library works. For my purpose I only needed to be compliant.

```
  s.dependency 'FBSDKCoreKit', '16.1.3'
  s.dependency 'FBSDKShareKit', '16.1.3'
  s.dependency 'TwitterKit5', '5.2.0'
  s.dependency 'TikTokOpenSDK', '~> 5.0.15'
  s.platform = :ios, '11.0'
```

@LecleVietnam If you update the sdk version that should be enough for everyone.

**Comment by LecleVietnam** [comment]
> @LecleVietnam I think the issue we are describing here is that the App cannot be pushed onto apple store, because it is still using deprecated APIs.
> 
> I managed to get it running changing this in **lecle_social_share.podspec**. Made sure to run all latest sdks. Twitter official sdk still fails, so I chose another one that is updated. I don't use twitter functions, so if you do make sure the library works. For my purpose I only needed to be compliant.
> 
> ```
>   s.dependency 'FBSDKCoreKit', '16.1.3'
>   s.dependency 'FBSDKShareKit', '16.1.3'
>   s.dependency 'TwitterKit5', '5.2.0'
>   s.dependency 'TikTokOpenSDK', '~> 5.0.15'
>   s.platform = :ios, '11.0'
> ```
> 
> @LecleVietnam If you update the sdk version that should be enough for everyone.

Thank you so much for your guidance and support! I truly appreciate your assistance in resolving the deprecated APIs issue. Based on your recommendations, I've successfully updated the dependencies in the lecle_social_share.podspec file, ensuring compatibility and compliance.

If you encounter any issues or have any questions regarding the package, please don't hesitate to notify me. Once again, thank you for your support!
