### ISSUE TITLE
[lecle_yoyo_player]update package_info_plus and wakelock

### ISSUE THREAD

**Issue by gusk9999** [LecleVietnam/LeclePackageIssue#35]
migrate wakelock to wakelock_plus and update package_info_plus to package version 4 or 5 please :).

**Comment by gusk9999** [comment]
Error:
Because every version of lecle_yoyo_player depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, every version of
  lecle_yoyo_player requires wakelock_windows ^0.2.0.
Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows
  requires win32 ^2.0.0 or ^3.0.0.
Thus, every version of lecle_yoyo_player requires win32 ^2.0.0 or ^3.0.0.
And because package_info_plus 5.0.0 depends on win32 >=4.0.0 <6.0.0 and no versions of package_info_plus match >5.0.0 <6.0.0, lecle_yoyo_player
  is incompatible with package_info_plus ^5.0.0.
So, because i_link_you depends on both package_info_plus ^5.0.0 and lecle_yoyo_player ^0.0.7, version solving failed.

**Comment by LecleVietnam** [comment]
thank you for supporting. i will update right now
