### ISSUE TITLE
[bug] Not able to install and run in iOS 

### ISSUE THREAD

**Issue by expoders8** [LecleVietnam/LeclePackageIssue#5]
I am trying to add your package in my app, it is working fine in android but when i installed in my iOS app then that time not able to run my application.

it gives me error of twittercorekit.
I added all those lines to my Info.plist file which you mention in package description. but when i'm trying to run app it gives me error if TwitterCoreKit .

I am not able to solve this error so can you please told me how to use your package in my iOS application 

Thank You ,

**Comment by LecleVietnam** [comment]
Hi @expoders8,
Can you provide us a screenshot about the error that you've met. Our team will take a look and fix this issue as soon as we complete the current project. Thank you.

**Comment by expoders8** [comment]
@LecleVietnam sure!!   The Error I got in lecle_social_share is mention below,

This is my run log:

Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...                                             42.6s
Running Xcode build...                                                  
Xcode build done.                                           138.9s
Failed to build iOS app
Error output from Xcode build:
↳
    * BUILD FAILED *


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/ly/wt6v9xs518x1d52md_08s_j00000gn/T/flutter_tools.bxSKWl/flutter_ios_build_temp_d
        ird0KxUe/temporary_xcresult_bundle

                                                      ^
1 warning generated.
1 warning generated.
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    error: the following command failed with exit code 0 but produced no further output
    SwiftEmitModule normal arm64 Emitting\ module\ for\ lecle_social_share (in target
    'lecle_social_share' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/Twitt
    erKit.framework/Headers/TWTRKit.h:22:9: note: while building module 'TwitterCore' imported from
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/Twitt
    erKit.framework/Headers/TWTRKit.h:22:
    #import <TwitterCore/TwitterCore.h>
            ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/TwitterCore.h"
            ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Headers/TwitterCore.h:35:1: warning: umbrella header for module 'TwitterCore'
    does not include header 'TWTRColorUtil.h'

    ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/Twitt
    erKit.framework/Headers/TWTRKit.h:22:9: note: while building module 'TwitterCore' imported from
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/Twitt
    erKit.framework/Headers/TWTRKit.h:22:
    #import <TwitterCore/TwitterCore.h>
            ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/TwitterCore.h"
            ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Headers/TwitterCore.h:35:1: warning: umbrella header for module 'TwitterCore'
    does not include header 'TWTRColorUtil.h'

    ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule
    'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                            ^
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterCore/iOS/Twit
    terCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to
    ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
    ld: building for iOS Simulator, but linking in dylib built for iOS, file
    '/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/Twit
    terKit.framework/TwitterKit' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Building targets in dependency order
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'nanopb' from
    project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'leveldb-library' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'gRPC-Core'
    from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every
    build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'gRPC-C++'
    from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every
    build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'abseil' from
    project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every
    build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'Try' from
    project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'TOCropViewController' from project 'Pods')
    warning: Run script build phase 'Run Script' will be run during every build because it does not
    specify any outputs. To address this warning, either add output dependencies to the script
    phase, or configure it to run in every build by unchecking "Based on dependency analysis" in
    the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does
    not specify any outputs. To address this warning, either add output dependencies to the script
    phase, or configure it to run in every build by unchecking "Based on dependency analysis" in
    the script phase. (in target 'Runner' from project 'Runner')
/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'PromisesObjC'
    from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'Libuv-gRPC'
    from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every
    build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'Libuv-gRPC' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'GoogleUtilities' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'GoogleSignIn-GoogleSignIn' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'GoogleSignIn'
    from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'GoogleDataTransport' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'GTMSessionFetcher' from project 'Pods')
/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'GTMAppAuth'
    from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'FirebaseInstallations' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'FirebaseCoreInternal' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'FirebaseCore'
    from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target
    'BoringSSL-GRPC' from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every
    build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'AppAuth' from
    project 'Pods')
    /Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'TwitterCore'
    from project 'Pods')
/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but
    the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'TwitterKit'
    from project 'Pods')

    Result bundle written to path:
        /var/folders/ly/wt6v9xs518x1d52md_08s_j00000gn/T/flutter_tools.bxSKWl/flutter_ios_build_temp_d
        ird0KxUe/temporary_xcresult_bundle


Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file
'/Users/apple/Projects/OpenGiving/Backup/OpenGiving_new_20_12_2022/ios/Pods/TwitterKit/iOS/TwitterK
it.framework/TwitterKit' for architecture arm64


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
    
    



### If I remove your package and run my application then it's working fine and not give me this error .
please help me to solve this error because I need your package in my application to share image

**Comment by LecleVietnam** [comment]
Hi @expoders8,
Thank you for the information. We will take a look and fix this issue asap.

**Comment by LecleVietnam** [comment]
Hi @expoders8, 
After checking your issue, we see that your issue is the same as [this issue](https://github.com/LecleVietnam/LeclePackageIssue/issues/2) which we have fixed before. Could you please update the package version and check this issue again? Thank you.

Our team has built the package on iPhone 14 Pro Max simulator and everything is fine.

**Comment by expoders8** [comment]
@LecleVietnam yes sure! let me check and inform you 
Thanks for your support
