### ISSUE TITLE
Cannot find 'TikTokOpenSDKShareFormatType' in scope

### ISSUE THREAD

**Issue by saileshbro** [LecleVietnam/LeclePackageIssue#7]
Hi, I tried to follow the docs from [here to setup TiktokSdk](https://developers.tiktok.com/doc/getting-started-ios-quickstart-swift/) but i am getting error.
Here's the error.

<pre>
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/x4/tpxhcc35793gpkx3g304sr040000gn/T/flutter_tools.2zvq4j/flutter_ios_build_temp_diruTLGm1/temporary_xcresult_bundle
    /Users/saileshbro/upwork/Robert/herd/ios/Pods/Toast/Toast/UIView+Toast.m:398:118: warning: 'UIActivityIndicatorViewStyleWhiteLarge' is deprecated: first deprecated in iOS 13.0 [-Wdeprecated-declarations]
        UIActivityIndicatorView *activityIndicatorView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          UIActivityIndicatorViewStyleLarge
    In module 'UIKit' imported from /Users/saileshbro/upwork/Robert/herd/ios/Pods/Target Support Files/Toast/Toast-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIActivityIndicatorView.h:18:5: note: 'UIActivityIndicatorViewStyleWhiteLarge' has been explicitly marked deprecated here
        UIActivityIndicatorViewStyleWhiteLarge API_DEPRECATED_WITH_REPLACEMENT("UIActivityIndicatorViewStyleLarge", ios(2.0, 13.0), tvos(9.0, 13.0)) = 0,
        ^
    1 warning generated.
    /Users/saileshbro/upwork/Robert/herd/ios/Pods/TwitterCore/iOS/TwitterCore.framework/Modules/module.private.modulemap:1:29: warning: private submodule 'TwitterCore.Private' in private module map, expected top-level module
    explicit module TwitterCore.Private {
                                ^
    /Users/saileshbro/upwork/Robert/herd/ios/Pods/TwitterCore/iOS/TwitterCore.framework/Modules/module.private.modulemap:1:29: note: rename 'TwitterCore.Private' to ensure it can be found by name
    explicit module TwitterCore.Private {
                                ^
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1258:47: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
            guard let view = UIApplication.shared.keyWindow?.rootViewController?.view else {
                                                  ^
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1264:30: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
            UIApplication.shared.keyWindow?.rootViewController?.present(activityViewController, animated: true, completion: nil)
                                 ^
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1345:51: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
                guard let view = UIApplication.shared.keyWindow?.rootViewController?.view else {
                                                      ^
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1540:25: error: cannot find type 'TikTokOpenSDKShareFormatType' in scope
                var format: TikTokOpenSDKShareFormatType!
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1552:26: error: cannot find 'TikTokOpenSDKShareFormatType' in scope
                    format = TikTokOpenSDKShareFormatType.normal
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/saileshbro/.pub-cache/hosted/pub.dartlang.org/lecle_social_share-0.5.0/ios/Classes/SwiftLecleSocialSharePlugin.swift:1554:26: error: cannot find 'TikTokOpenSDKShareFormatType' in scope
                    format = TikTokOpenSDKShareFormatType.greenScreen
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

</pre>

**Comment by saileshbro** [comment]
Here is my `AppDelegate.swift` file
```swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        FirebaseApp.configure()
        FBSDKCoreKit.ApplicationDelegate.shared.application(
            application,
            didFinishLaunchingWithOptions: launchOptions
        );
        FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
            GeneratedPluginRegistrant.register(with: registry)
        }
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        }
        TikTokOpenSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
        GeneratedPluginRegistrant.register(with: self)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

}

```

**Comment by saileshbro** [comment]
And the podfile
```ruby

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.3.0'
  pod 'TikTokOpenSDK', '~> 5.0.14'
  # share_handler addition start
  target 'ShareExtension' do
    inherit! :search_paths
    pod "share_handler_ios_models", :path => ".symlinks/plugins/share_handler_ios/ios/Models"
  end
  # share_handler addition end
end
```

**Comment by LecleVietnam** [comment]
Hi @saileshbro, 
Thank you for your feedback, our team will consider and working on this issue asap.

**Comment by LecleVietnam** [comment]
Hi @saileshbro,
Because our team are currently busy with another project so we can not check your issue soon, we are very sorry about this.

After checking your issue we found that your issue occurs because the configuration for your application is not correct (We have tested our package in a new project and everything is fine). Therefore, we have update the iOS config instruction in the package's document. Could you please update your app configuration based on our document update and check this issue again. Thank you.

**Comment by saileshbro** [comment]
@LecleVietnam Cool, thanks for the heads up. I will try changing the configs.
