### ISSUE TITLE
rewind 2 minutes back  on live stream start?

### ISSUE THREAD

**Issue by babakoto** [LecleVietnam/LeclePackageIssue#8]
Hello 
Is it possible to rewind 2 minutes back a live stream, like facebook, youtube?
example please 🙏 
Thanks

**Comment by LecleVietnam** [comment]
Hi @babakoto,
Did you mean that you want to have a custom duration for the rewind and forward buttons?

**Comment by babakoto** [comment]
Hi @LecleVietnam 
Like this 


when the user wants to follow live
<img width="903" alt="image" src="https://user-images.githubusercontent.com/44688702/215421312-15289ee9-1637-4358-b278-636e9dcc01ad.png">

when the user wants to select x minute back from live video
<img width="903" alt="image" src="https://user-images.githubusercontent.com/44688702/215422158-c2a9a139-aa5a-43ba-ad4f-949f90e2a2ab.png">

**Comment by LecleVietnam** [comment]
Hi @babakoto,
We have understood what you mean, our team will consider this issue and update the package asap.

**Comment by babakoto** [comment]
Thanks, I would like it to be possible to choose between live and watching what has already happened

**Comment by LecleVietnam** [comment]
Hi @babakoto,
Our team has considered your suggestion and update the lecle_yoyo_player package based on it. Could you please update the lecle_yoyo_player package to the latest version and check this issue again?. You can check the package's document to see the feature related properties.

Thank you.
